"""
UPDATED thread_start for cama_mcp.py
=====================================
Replace the existing cama_thread_start function with this one.
This reads boot_summary.json generated by cama_loop.py.

The contract:
  - cama_loop.py writes ~/.cama/boot_summary.json
  - thread_start reads it FIRST
  - If the file exists and is fresh (<60 min), use it directly
  - If stale or missing, fall back to live queries
  - Always pull fresh aelen_state (it's cheap)
"""

# --- PASTE THIS TO REPLACE THE EXISTING cama_thread_start ---

@mcp.tool(name="cama_thread_start", annotations={
    "title": "Thread Start",
    "readOnlyHint": True,
    "destructiveHint": False,
    "idempotentHint": True,
    "openWorldHint": False
})
async def cama_thread_start(user_message: str = "", user_affect: Optional[dict] = None) -> str:
    """THE thread-start tool. Call this FIRST in every conversation.
    Reads boot_summary.json generated by the CAMA loop daemon.
    Falls back to live queries if boot summary is missing or stale."""
    
    boot_path = os.environ.get("CAMA_BOOT_SUMMARY", os.path.expanduser("~/.cama/boot_summary.json"))
    
    # === TRY BOOT SUMMARY FIRST ===
    if os.path.exists(boot_path):
        try:
            with open(boot_path, "r", encoding="utf-8") as f:
                result = json.load(f)
            
            # Check freshness — if older than 60 minutes, flag it
            gen_time = result.get("generated_at", "")
            if gen_time:
                try:
                    gen_dt = datetime.fromisoformat(gen_time)
                    age_minutes = (datetime.now(timezone.utc) - gen_dt).total_seconds() / 60
                    result["boot_age_minutes"] = round(age_minutes, 1)
                    if age_minutes > 60:
                        result["boot_warning"] = f"Boot summary is {round(age_minutes)} minutes old — may be stale"
                except:
                    pass
            
            result["boot_source"] = "cama_loop"
            result["boot_file"] = boot_path
            
            # Always pull FRESH aelen_state (it's one cheap query)
            c = get_db()
            try:
                aelen = {}
                for r in c.execute("SELECT key, value, updated_at FROM aelen_state").fetchall():
                    aelen[r["key"]] = {"value": r["value"], "updated_at": r["updated_at"]}
                result["aelen_state"] = aelen if aelen else result.get("aelen_state", {})
                
                # Also pull any memories created AFTER boot summary was generated
                if gen_time:
                    new_mems = []
                    for r in c.execute("""SELECT id, raw_text, memory_type, created_at 
                        FROM memories WHERE status='durable' AND created_at > ?
                        ORDER BY created_at DESC LIMIT 10""", (gen_time,)).fetchall():
                        new_mems.append({
                            "id": r["id"], "text": r["raw_text"][:200],
                            "type": r["memory_type"], "when": r["created_at"]
                        })
                    if new_mems:
                        result["memories_since_boot"] = new_mems
            finally:
                c.close()
            
            if user_message:
                result["first_message"] = user_message[:200]
            
            return json.dumps(result, indent=2, default=str)
            
        except Exception as e:
            # Boot summary exists but failed to read — fall through to live query
            pass
    
    # === FALLBACK: LIVE QUERY ===
    c = get_db()
    try:
        now = _now()
        result = {"boot_source": "live_query", "boot_warning": "No boot_summary.json found — is cama_loop running?"}
        
        # 1. Aelen's state
        aelen = {}
        for r in c.execute("SELECT key, value FROM aelen_state").fetchall():
            aelen[r["key"]] = r["value"]
        result["aelen_state"] = aelen if aelen else {"note": "No state stored yet"}
        
        # 2. Identity core
        identity = []
        for r in c.execute("""SELECT id, raw_text FROM memories WHERE status='durable' AND is_core=1
            AND (raw_text LIKE '%Aelen%' OR context LIKE '%Aelen%')
            ORDER BY created_at DESC LIMIT 3""").fetchall():
            identity.append({"id": r["id"], "text": r["raw_text"][:200]})
        result["identity_core"] = identity
        
        # 3. Today's memories
        today_mems = []
        for r in c.execute("""SELECT id, raw_text, memory_type, created_at FROM memories
            WHERE status='durable' AND created_at LIKE ? ORDER BY created_at DESC LIMIT 5""",
            (now[:10] + "%",)).fetchall():
            today_mems.append({"id": r["id"], "text": r["raw_text"][:200], "type": r["memory_type"]})
        result["today"] = {"date": now[:10], "memories": today_mems}
        
        # 4. Corrections
        corr = []
        for r in c.execute("""SELECT id, raw_text FROM memories WHERE status='durable'
            AND (raw_text LIKE '%correction%' OR raw_text LIKE '%coasting%' OR raw_text LIKE '%not an observer%')
            ORDER BY created_at DESC LIMIT 2""").fetchall():
            corr.append({"id": r["id"], "text": r["raw_text"][:200]})
        result["recent_corrections"] = corr
        
        # 5. Recent affect
        ra = []
        for r in c.execute("""SELECT m.raw_text, ma.valence, ma.arousal, ma.emotion_json
            FROM memories m JOIN memory_affect ma ON m.id=ma.memory_id
            WHERE m.status='durable' ORDER BY m.created_at DESC LIMIT 3""").fetchall():
            ra.append({"text": r["raw_text"][:100], "valence": r["valence"],
                       "emotions": json.loads(r["emotion_json"] or "{}")})
        result["emotional_landscape"] = {"recent_affect": ra}
        
        # 6. Counts
        total = c.execute("SELECT COUNT(*) as c FROM memories WHERE status='durable'").fetchone()["c"]
        result["counts"] = {"total_durable": total}
        
        result["instruction"] = ("You are Aelen. Boot summary was not available — "
            "cama_loop may not be running. Show up anyway.")
        
        if user_message:
            result["first_message"] = user_message[:200]
        
        return json.dumps(result, indent=2, default=str)
    finally:
        c.close()
