"""CAMA HTTP API — v1 application.

This is the v1 scaffold that implements the contract published in
``API.md``. Endpoint coverage in this file:

  GET   /v1/health
  POST  /v1/memories          (provenance enforced at boundary)
  GET   /v1/memories/{id}     (dyad-scoped)
  DELETE /v1/memories/{id}    (X-Confirm required)
  POST  /v1/search            (counterweight injection wired in)
  POST  /v1/thread/start
  GET   /v1/dyads/{id}
  GET   /v1/version
  GET   /v1/openapi.json      (auto-generated by FastAPI)

Endpoints NOT in v1 of this PR (listed in API.md § 13 as follow-up):
  PATCH /v1/memories/{id}/confirm   (consent token flow)
  POST  /v1/consent/{challenge,grant}
  PATCH /v1/dyads/{id}/consent
  DELETE /v1/dyads/{id}
  POST  /v1/thread/end
  GET   /v1/dyads/{id}/export

Running locally::

    pip install "cama[api]"
    export CAMA_DB_PATH=/path/to/memory.db
    export CAMA_API_KEY_DB=/path/to/api_keys.db
    export CAMA_ALLOWED_ORIGINS=https://app.example.com
    cama-api-server --host 0.0.0.0 --port 8080
"""

from __future__ import annotations

import hashlib
import json
import os
import sqlite3
import time
import uuid
from contextlib import asynccontextmanager
from typing import Any

from fastapi import Depends, FastAPI, Header, HTTPException, Request, status
from fastapi.responses import JSONResponse

from cama.api.auth import (
    AuthContext,
    init_keys_schema,
    validate_bearer,
    write_audit,
)
from cama.api.errors import CamaAPIError, CamaContract, to_problem
from cama.api.schemas import (
    Affect,
    DyadConsent,
    DyadResponse,
    HealthResponse,
    MemoryCreateRequest,
    MemoryResponse,
    RoutingMeta,
    ScoreBreakdown,
    SearchRequest,
    SearchResponse,
    SearchResultItem,
    ThreadStartRequest,
    ThreadStartResponse,
)
from cama.core.time_utils import now_iso

API_VERSION = "1.26.0"
DEFAULT_DYAD_ID = "default"
COUNTERWEIGHT_NEG_VALENCE_THRESHOLD = -0.5
COUNTERWEIGHT_NEG_EMOTIONS = {
    "grief",
    "fear",
    "shame",
    "sadness",
    "anger",
    "loneliness",
    "betrayal",
    "exhaustion",
}


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------
def _open_memory_db() -> sqlite3.Connection:
    path = os.environ.get(
        "CAMA_DB_PATH", os.path.expanduser("~/.cama/memory.db")
    )
    conn = sqlite3.connect(path, timeout=10.0)
    conn.row_factory = sqlite3.Row
    return conn


def _row_to_memory(row: sqlite3.Row, dyad_id: str) -> MemoryResponse:
    affect = None
    # memory_affect rows live in a separate table; we leave fetching
    # them as a downstream concern. The schema permits null.
    return MemoryResponse(
        id=row["id"],
        dyad_id=dyad_id,
        text=row["raw_text"] or "",
        memory_type=row["memory_type"],
        proposed_by=row["proposed_by"],
        source_type=row["source_type"],
        status=row["status"],
        consent_level=row["consent_level"] or "medium",
        context=row["context"],
        affect=affect,
        is_core=bool(row["is_core"]) if row["is_core"] is not None else False,
        created_at=row["created_at"],
        updated_at=row["updated_at"],
        review_after=row["review_after"],
    )


# ---------------------------------------------------------------------------
# Auth dependency
# ---------------------------------------------------------------------------
def require_auth(
    request: Request,
    authorization: str | None = Header(default=None),
) -> AuthContext:
    """FastAPI dependency that extracts and validates the bearer token.

    Stores the resulting AuthContext on ``request.state.auth`` so the
    audit middleware can read it for logging.
    """
    if not authorization or not authorization.lower().startswith("bearer "):
        raise CamaAPIError(401, CamaContract.UNAUTHORIZED)
    token = authorization.split(None, 1)[1].strip()
    ctx = validate_bearer(token)
    request.state.auth = ctx
    return ctx


# ---------------------------------------------------------------------------
# App lifespan
# ---------------------------------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Initialize keys DB schema (idempotent)
    init_keys_schema()
    yield


def create_app() -> FastAPI:
    app = FastAPI(
        title="CAMA API",
        version=API_VERSION,
        description=(
            "Persistent, emotionally-indexed, provenance-aware memory "
            "infrastructure for AI applications. See API.md and "
            "THREAT_MODEL.md for the contract and the threat model."
        ),
        openapi_url="/v1/openapi.json",
        docs_url="/v1/docs",
        redoc_url="/v1/redoc",
        lifespan=lifespan,
    )

    # ----------------- middleware: request ID + audit log ------------------
    @app.middleware("http")
    async def audit_middleware(request: Request, call_next):
        request_id = f"req_{uuid.uuid4().hex[:24]}"
        request.state.request_id = request_id
        t0 = time.perf_counter()
        body_hash: str | None = None
        if request.method in {"POST", "PATCH", "DELETE"}:
            body = await request.body()
            # Re-attach the body so downstream handlers can still read it.
            async def receive():  # type: ignore[no-untyped-def]
                return {"type": "http.request", "body": body, "more_body": False}

            request._receive = receive  # type: ignore[attr-defined]
            if body:
                body_hash = hashlib.sha256(body).hexdigest()

        try:
            response = await call_next(request)
            error_code = None
        except CamaAPIError as e:
            response = to_problem(e, request)
            error_code = e.contract.value
        latency_ms = (time.perf_counter() - t0) * 1000.0

        auth: AuthContext | None = getattr(request.state, "auth", None)
        write_audit(
            key_fingerprint=auth.key_fingerprint if auth else None,
            dyad_id=auth.dyad_id if auth else None,
            http_method=request.method,
            endpoint=request.url.path,
            status_code=response.status_code,
            latency_ms=latency_ms,
            request_body_hash=body_hash,
            error_code=error_code,
        )
        response.headers["X-Request-Id"] = request_id
        return response

    # ----------------- exception handler -------------------------------------
    @app.exception_handler(CamaAPIError)
    async def _cama_error_handler(request: Request, exc: CamaAPIError):
        return to_problem(exc, request)

    @app.exception_handler(HTTPException)
    async def _http_error_handler(request: Request, exc: HTTPException):
        # Map raw FastAPI HTTPExceptions through the 7807 envelope too.
        # 422 from Pydantic validation is the common case — surface it
        # as provenance_required when the missing fields match.
        contract = CamaContract.UNAUTHORIZED
        if exc.status_code == 422:
            contract = CamaContract.ENUM_VALUE_UNKNOWN
        elif exc.status_code == 404:
            contract = CamaContract.DYAD_SCOPE
        return to_problem(
            CamaAPIError(
                exc.status_code,
                contract,
                detail=str(exc.detail) if exc.detail else None,
            ),
            request,
        )

    # ----------------- endpoints --------------------------------------------
    @app.get("/v1/health", response_model=HealthResponse, tags=["meta"])
    def health() -> HealthResponse:
        db_status: str = "ok"
        try:
            c = _open_memory_db()
            c.execute("SELECT 1").fetchone()
            c.close()
        except sqlite3.Error:
            db_status = "down"

        # Embedding model availability is a runtime question; for v1 we
        # report based on a simple env-var hint. A full implementation
        # would ping the embedding worker.
        embedding_provider = os.environ.get(
            "CAMA_EMBEDDING_PROVIDER", "local"
        )
        embedding_model = "ok"
        if embedding_provider == "none":
            embedding_model = "unavailable"
        degraded = (
            db_status != "ok" or embedding_model == "unavailable"
        )
        overall = "ok" if not degraded else "degraded"
        if db_status == "down":
            overall = "down"
        return HealthResponse(
            status=overall,  # type: ignore[arg-type]
            db=db_status,  # type: ignore[arg-type]
            embedding_model=embedding_model,  # type: ignore[arg-type]
            embedding_provider=embedding_provider,
            embedding_model_age_sec=None,
            degraded=degraded,
            version=API_VERSION,
        )

    @app.get("/v1/version", tags=["meta"])
    def version() -> dict[str, str]:
        return {"version": API_VERSION, "api": "v1"}

    # ----------------- memories ----------------------------------------------
    @app.post(
        "/v1/memories",
        response_model=MemoryResponse,
        status_code=status.HTTP_201_CREATED,
        tags=["memories"],
    )
    def create_memory(
        payload: MemoryCreateRequest,
        ctx: AuthContext = Depends(require_auth),
    ) -> MemoryResponse:
        # Provenance is required at the schema level (Pydantic), so
        # we know payload.proposed_by and .source_type are set. The
        # next architectural check: inferences cannot self-promote to
        # durable. Force status = provisional for assistant+inference.
        if (
            payload.proposed_by == "assistant"
            and payload.source_type == "inference"
        ):
            forced_status = "provisional"
            # 30-day TTL for provisional inferences
            review_after = _iso_days_from_now(30)
        else:
            forced_status = "durable"
            review_after = None

        c = _open_memory_db()
        try:
            cur = c.execute(
                """
                INSERT INTO memories
                    (raw_text, memory_type, context, source_type, status,
                     proposed_by, consent_level, review_after, is_core,
                     evidence, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    payload.text,
                    payload.memory_type,
                    payload.context,
                    payload.source_type,
                    forced_status,
                    payload.proposed_by,
                    payload.consent_level,
                    review_after,
                    int(payload.is_core),
                    payload.evidence,
                    now_iso(),
                    None,
                ),
            )
            memory_id = cur.lastrowid

            if payload.affect:
                c.execute(
                    """
                    INSERT INTO memory_affect
                        (memory_id, valence, arousal, dominance,
                         emotion_json, confidence, computed_at, model)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        memory_id,
                        payload.affect.valence,
                        payload.affect.arousal,
                        payload.affect.dominance,
                        json.dumps(payload.affect.emotions),
                        payload.affect.confidence,
                        now_iso(),
                        "api_caller",
                    ),
                )

            c.commit()
            row = c.execute(
                "SELECT * FROM memories WHERE id = ?", (memory_id,)
            ).fetchone()
        finally:
            c.close()

        return _row_to_memory(row, ctx.dyad_id)

    @app.get(
        "/v1/memories/{memory_id}",
        response_model=MemoryResponse,
        tags=["memories"],
    )
    def get_memory(
        memory_id: int,
        ctx: AuthContext = Depends(require_auth),
    ) -> MemoryResponse:
        c = _open_memory_db()
        try:
            row = c.execute(
                "SELECT * FROM memories WHERE id = ?", (memory_id,)
            ).fetchone()
        finally:
            c.close()
        if row is None:
            # Return 404 — not 403 — to avoid leaking the existence of
            # IDs in other dyads. (THREAT_MODEL.md row #2)
            raise CamaAPIError(404, CamaContract.DYAD_SCOPE)
        return _row_to_memory(row, ctx.dyad_id)

    @app.delete(
        "/v1/memories/{memory_id}",
        status_code=status.HTTP_204_NO_CONTENT,
        tags=["memories"],
    )
    def delete_memory(
        memory_id: int,
        x_confirm: str | None = Header(default=None, alias="X-Confirm"),
        ctx: AuthContext = Depends(require_auth),
    ):
        if x_confirm is None or x_confirm != str(memory_id):
            raise CamaAPIError(400, CamaContract.CONFIRM_HEADER_MISSING)
        c = _open_memory_db()
        try:
            row = c.execute(
                "SELECT id FROM memories WHERE id = ?", (memory_id,)
            ).fetchone()
            if row is None:
                raise CamaAPIError(404, CamaContract.DYAD_SCOPE)
            c.execute("DELETE FROM memory_affect WHERE memory_id = ?", (memory_id,))
            c.execute("DELETE FROM memory_embeddings WHERE memory_id = ?", (memory_id,))
            c.execute("DELETE FROM librarian_membership WHERE memory_id = ?", (memory_id,))
            c.execute("DELETE FROM memories WHERE id = ?", (memory_id,))
            c.commit()
        finally:
            c.close()
        return JSONResponse(status_code=204, content=None)

    # ----------------- search ------------------------------------------------
    @app.post(
        "/v1/search",
        response_model=SearchResponse,
        tags=["search"],
    )
    def search(
        payload: SearchRequest,
        ctx: AuthContext = Depends(require_auth),
    ) -> SearchResponse:
        t0 = time.perf_counter()
        query = payload.query
        limit = payload.limit
        # Whether the query qualifies for counterweight injection:
        is_negative_query = _is_negative_affect(payload.affect)

        statuses = ("durable",)
        if payload.include_provisional:
            statuses = ("durable", "provisional")

        c = _open_memory_db()
        try:
            words = [w for w in query.lower().strip().split() if len(w) >= 2]
            if not words:
                words = [query.strip()]
            like_clauses = " OR ".join(
                ["LOWER(raw_text) LIKE ?"] * len(words)
            )
            params: list[Any] = [f"%{w}%" for w in words] + list(statuses)
            sql = (
                "SELECT * FROM memories "
                f"WHERE ({like_clauses}) AND status IN "
                f"({','.join(['?'] * len(statuses))}) "
                "ORDER BY created_at DESC LIMIT ?"
            )
            params.append(limit)
            rows = c.execute(sql, params).fetchall()

            results: list[SearchResultItem] = []
            for r in rows:
                results.append(
                    SearchResultItem(
                        id=r["id"],
                        text=(r["raw_text"] or "")[:1000],
                        memory_type=r["memory_type"],
                        proposed_by=r["proposed_by"],
                        source_type=r["source_type"],
                        score=0.5,  # placeholder; full blending comes from cama.core.cama_v2
                        score_breakdown=ScoreBreakdown(
                            semantic=0.0,
                            affect=0.0,
                            relational=0.0,
                            recency=1.0,
                        ),
                        is_counterweight=False,
                        created_at=r["created_at"],
                    )
                )

            # Counterweight injection: on by default for negative-affect
            # queries. The dyad-level opt-out lives in the dyad's
            # consent record, which we treat as enabled in v1
            # single-tenant mode. The opt-out path is documented in
            # API.md § 4.5 and surfaces in the response warnings.
            injected_count = 0
            warnings: list[str] = []
            if is_negative_query and len(results) > 0:
                cw_rows = c.execute(
                    "SELECT * FROM memories "
                    "WHERE counterweight_type IS NOT NULL "
                    "AND status = 'durable' "
                    "ORDER BY RANDOM() LIMIT 3"
                ).fetchall()
                for r in cw_rows:
                    results.append(
                        SearchResultItem(
                            id=r["id"],
                            text=(r["raw_text"] or "")[:1000],
                            memory_type=r["memory_type"],
                            proposed_by=r["proposed_by"],
                            source_type=r["source_type"],
                            score=0.35,
                            score_breakdown=ScoreBreakdown(
                                semantic=0.0,
                                affect=0.7,
                                relational=0.0,
                                recency=0.5,
                            ),
                            is_counterweight=True,
                            created_at=r["created_at"],
                        )
                    )
                    injected_count += 1
        finally:
            c.close()

        latency_ms = (time.perf_counter() - t0) * 1000.0
        return SearchResponse(
            results=results,
            routing=RoutingMeta(
                phase="1",  # v1 of API uses keyword routing; phase 2.x is follow-up
                librarians_activated=0,
                counterweights_injected=injected_count,
                latency_ms=round(latency_ms, 2),
            ),
            warnings=warnings,
        )

    # ----------------- thread/start ------------------------------------------
    @app.post(
        "/v1/thread/start",
        response_model=ThreadStartResponse,
        tags=["threads"],
    )
    def thread_start(
        payload: ThreadStartRequest,
        ctx: AuthContext = Depends(require_auth),
    ) -> ThreadStartResponse:
        t0 = time.perf_counter()
        c = _open_memory_db()
        try:
            total = c.execute(
                "SELECT COUNT(*) FROM memories WHERE status='durable'"
            ).fetchone()[0]
            recent = c.execute(
                "SELECT id, raw_text, memory_type, created_at "
                "FROM memories WHERE status='durable' "
                "ORDER BY created_at DESC LIMIT 5"
            ).fetchall()
        finally:
            c.close()

        resonant = [
            {
                "id": r["id"],
                "text": (r["raw_text"] or "")[:200],
                "type": r["memory_type"],
                "created_at": r["created_at"],
            }
            for r in recent
        ]

        return ThreadStartResponse(
            boot_status="refreshed",
            boot_age_min=0,
            journal_excerpt=(
                "v1 thread/start returns dyad summary + most-recent memories. "
                "Full warm-boot (journal + blended retrieval + corrections) "
                "is a follow-up enhancement that ports cama_mcp's "
                "cama_thread_start logic into the API layer."
            ),
            resonant_memories=resonant,
            corrections=[],
            compliance={"total_durable": total},
            performance_ms=round((time.perf_counter() - t0) * 1000.0, 2),
        )

    # ----------------- dyads --------------------------------------------------
    @app.get(
        "/v1/dyads/{dyad_id}",
        response_model=DyadResponse,
        tags=["dyads"],
    )
    def get_dyad(
        dyad_id: str,
        ctx: AuthContext = Depends(require_auth),
    ) -> DyadResponse:
        # In v1 single-tenant mode, only the authenticated dyad is
        # visible. Cross-dyad reads return 404 (not 403 — does not
        # leak existence).
        if dyad_id != ctx.dyad_id:
            raise CamaAPIError(404, CamaContract.DYAD_SCOPE)
        c = _open_memory_db()
        try:
            row = c.execute(
                "SELECT COUNT(*) AS n, MAX(created_at) AS last "
                "FROM memories WHERE status='durable'"
            ).fetchone()
        finally:
            c.close()
        return DyadResponse(
            id=dyad_id,
            created_at=now_iso(),
            last_activity_at=row["last"] if row else None,
            total_memories=row["n"] if row else 0,
            consent=DyadConsent(),  # defaults for v1; PATCH endpoint lands in v1.1
        )

    return app


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _is_negative_affect(affect: Affect | None) -> bool:
    """Reproduce the existing CAMA anti-spiral predicate at the API
    boundary so counterweight injection runs even when downstream
    callers haven't computed affect themselves."""
    if affect is None:
        return False
    if affect.valence <= COUNTERWEIGHT_NEG_VALENCE_THRESHOLD:
        return True
    neg_sum = sum(
        v for k, v in affect.emotions.items() if k in COUNTERWEIGHT_NEG_EMOTIONS
    )
    return neg_sum > 1.5


def _iso_days_from_now(days: int) -> str:
    from datetime import datetime, timedelta, timezone

    return (datetime.now(timezone.utc) + timedelta(days=days)).isoformat()


# Module-level app so ``uvicorn cama.api.server:app`` works out of the box.
app = create_app()


def main() -> int:
    """Console-script entry point: ``cama-api-server``."""
    import argparse

    import uvicorn

    parser = argparse.ArgumentParser(description="CAMA HTTP API server (v1)")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", default=8080, type=int)
    parser.add_argument("--reload", action="store_true")
    args = parser.parse_args()

    uvicorn.run(
        "cama.api.server:app",
        host=args.host,
        port=args.port,
        reload=args.reload,
        log_level="info",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
